#include<iostream>
using namespace std;

 main()
{
   int num,den,quo,rem;
   cout<<"---------------------------------------"<<endl;
cout<<"Author Name : Sahil Sao"<<endl;
cout<<"Class       : MCA I SEM"<<endl;
cout<<"Path        : D:\\Sahil C++ Assignment\\1.quo_rem.cpp"<<endl;
cout<<"---------------------------------------"<<endl;
  cout<<"Enter Numerator "<<endl;
  cin>>num;
  cout<<"Enter Denominator "<<endl;
  cin>>den;
  quo=num/den;
  rem=num%den;
  cout<<"Quotient is "<<quo;
   cout<<"\nRemainder is "<<rem;
    return 0;
    }
