#include<iostream>
using namespace std;
int main()
{
   int num;
   cout<<"---------------------------------------"<<endl;
cout<<"Author Name : Sahil Sao"<<endl;
cout<<"Class       : MCA I SEM"<<endl;
cout<<"Path        : D:\\Sahil C++ Assignment\\3.even_odd.cpp"<<endl;
cout<<"---------------------------------------"<<endl;
  cout<<"Enter no: ";
  cin>>num;
  if(num%2==0)
     cout<<"Number is even";
     else cout<<"Number is odd";
    return 0;
    }
